//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pro1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portofolio
    {
        public int Prt_Id { get; set; }
        public string Prt_Name { get; set; }
        public Nullable<System.DateTime> Prt_Date { get; set; }
        public string Prt_Client { get; set; }
        public string Prt_Categry { get; set; }
        public string Prt_img { get; set; }
    }
}
