//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pro1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int tm_Id { get; set; }
        public string tm_Name { get; set; }
        public string tm_job { get; set; }
        public string tm_Tw { get; set; }
        public string tm_Fc { get; set; }
        public string tm_Ln { get; set; }
        public string tm_img { get; set; }
    }
}
